### ISSUE TITLE
Plugin not able to check app availability in Android 11 devices

### ISSUE THREAD

**Issue by tusharagaarwal** [nchutchind/App-Launcher-Cordova-Plugin#41]
Plugin is not able to check if app is installed in Android 11 devices using either package name or custom URI scheme. Tested and working on all devices running in lower versions of android.

###### Error:  
> 2021-09-27 14:47:31.772 19270-19666/com.invokerApp D/Launcher Plugin: No Activities found that handle uri: sampleApp://

**Comment by samcsyu** [comment]
Please try to specify package name to be checked in AndroidManifest.xml, inside the <queries> tag, which is required for Android 11. Please see following link for details

https://developer.android.com/training/package-visibility/declaring

**Comment by Jackson-park** [comment]
<queries>
        <package android:name="com.example.store" />
</queries>

If you add this content, it has been confirmed that it works normally.
Is there a way to automatically input the platform when adding it?

**Comment by tusharagaarwal** [comment]
@samcsyu yes adding the package name in query list in AndroidManifest.xml will allow me to access the installed package list.
Thanks for the information.
