### ISSUE TITLE
App not launching in ios

### ISSUE THREAD

**Issue by anr2411** [nchutchind/App-Launcher-Cordova-Plugin#9]
I am trying to launch one app from another app. But it's not working in ios.

I have two apps 'A' and 'B'. Url scheme of app 'B' is ' xyz '. If I used Url scheme of app 'B' in safari then it opens that app. But when I try to do it from app 'A' using following method, it gives error of app not being installed:

window.plugins.launcher.launch({uri:"xyz://"},
          function(json){//alert("Success : "+ json)
          },
          function(err){alert("Install  App.")}); 

I would like to know what I am doing wrong in this.

**Comment by mrmasterix** [comment]
@anr2411, what is your iOS version?

**Comment by anr2411** [comment]
@mrmasterix, iOS version is 9.3.3

**Comment by anr2411** [comment]
@mrmasterix  any updates?

**Comment by mrmasterix** [comment]
@anr2411, unfortunately not.

**Comment by anr2411** [comment]
Solution:
 
1. Add this in config.xml of your app:
       <allow-navigation href="customSchemeName://*/*" />

2. Add this in platforms/ios/<appname>/<appname>-Info.plist

     <key>LSApplicationQueriesSchemes</key>
        <array>
             <string>customSchemeName</string>
        </array>
